# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkmDJpH2ZNKwDZgsk4A3GvHln4Z51pMr
"""

import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(0, 2 * np.pi, 1000)

y = np.sin(t)
plt.figure(figsize=(8, 6))
plt.plot(t, y, label='y = sin(t)', color='blue')
plt.title("Sinus Funksiyasining Grafigi")
plt.xlabel("t o'qi")
plt.ylabel("y o'qi")
plt.axhline(0, color='black', linewidth=0.8)
plt.axvline(0, color='black', linewidth=0.8)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

np.random.seed(42)
x_random = np.random.rand(100)
y_random = np.random.rand(100)

plt.figure(figsize=(8, 6))
plt.scatter(x_random, y_random, color='red', alpha=0.6, edgecolor='black')
plt.title("Tasodifiy Nuqtalar Scatter Grafigi")
plt.xlabel("X o'qi")
plt.ylabel("Y o'qi")
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

import pandas as pd

# CSV faylni GitHub-dan yuklash
url = "https://raw.githubusercontent.com/Zulayho06/Maxsus-topshiriq/main/WHO%20COVID-19%20cases.csv"
data = pd.read_csv(url)

# Ma'lumotlarni ko'rish
print("Dastlabki 5 qator:\n", data.head())

# Filtrlash: Masalan, "New_cases" ustunidagi qiymatlar > 10000
filtered_data = data[data['New_cases'] > 10000]

print("\nFiltrlangan ma'lumotlar:\n", filtered_data)

# Filtrlangan ma'lumotlarni saqlash
filtered_data.to_csv("Filtered_COVID19_Cases.csv", index=False)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("acer.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("hp.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("macc.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

"""# Новый раздел"""